metadata_dir = "/var/lib/garage/meta"

data_dir = "/var/lib/garage/data"

db_engine = "sqlite"
replication_factor = 1

rpc_bind_addr = "[::]:3901"
rpc_public_addr = "garage:3901"

# Replace this value for any non-local deployment.
rpc_secret = "REPLACE_WITH_64_HEX_CHARS"

[s3_api]
# Must match the S3 client region.
s3_region = "us-east-1"
api_bind_addr = "[::]:3900"

# Optional, only required for vhost-style requests.
root_domain = ".s3.garage.local"

[admin]
api_bind_addr = "[::]:3903"

# Replace this token for any non-local deployment.
admin_token = "REPLACE_WITH_ADMIN_TOKEN"
metrics_token = "REPLACE_WITH_METRICS_TOKEN"
